/* Write your PL/SQL query statement below */
SELECT DISTINCT T1.NUM AS ConsecutiveNums FROM LOGS T1 JOIN LOGS T2 ON T1.ID=T2.ID+1  JOIN LOGS T3 ON T2.ID+1=T3.ID+2 WHERE T1.NUM=T2.NUM AND T2.NUM=T3.NUM;
